using System.Threading.Tasks;
using UnityEngine;

/// <summary>
/// Coordinates the startup sequence for the prototype game scene.
/// This manager owns execution order only. It does not generate the world,
/// generate pawn profile data, or spawn pawns directly.
/// </summary>
public class GameFlowManager : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private WorldGenerator m_worldGenerator;
    [SerializeField] private PawnGenerationManager m_pawnGenerationManager;
    [SerializeField] private PawnManager m_pawnManager;

    [Header("Startup Settings")]
    [SerializeField] private bool m_startOnSceneStart = true;
    [SerializeField] private bool m_autoGenerateDebugStarterPawns = true;

    [Header("Debug")]
    [SerializeField] private bool m_logStateChanges = true;

    private GameFlowState m_currentState = GameFlowState.NotStarted;

    public GameFlowState CurrentState
    {
        get { return m_currentState; }
    }

    /// <summary>
    /// Starts the prototype startup flow when the scene starts.
    /// </summary>
    private async void Start()
    {
        if (!m_startOnSceneStart)
        {
            return;
        }

        await StartGameFlowAsync();
    }

    /// <summary>
    /// Runs the current startup sequence:
    /// generate starter pawn profiles, generate world, spawn generated starter pawns,
    /// then mark the game as ready.
    /// </summary>
    public async Task StartGameFlowAsync()
    {
        if (m_currentState != GameFlowState.NotStarted)
        {
            Debug.LogWarning("GameFlowManager startup ignored because flow has already started.", this);
            return;
        }

        if (!HasRequiredReferences())
        {
            SetState(GameFlowState.Failed);
            return;
        }

        try
        {
            if (m_autoGenerateDebugStarterPawns)
            {
                SetState(GameFlowState.GeneratingStarterPawns);
                m_pawnGenerationManager.GenerateDebugStarterPawnProfiles();
            }
            else
            {
                SetState(GameFlowState.WaitingForStarterPawnSelection);
                Debug.LogWarning(
                    "GameFlowManager is waiting for starter pawn selection, but pawn picker UI is not implemented yet.",
                    this);

                SetState(GameFlowState.Failed);
                return;
            }

            SetState(GameFlowState.GeneratingWorld);
            await m_worldGenerator.GenerateWorldAsync();

            SetState(GameFlowState.SpawningStarterPawns);
            m_pawnManager.SpawnStarterPawns(m_pawnGenerationManager.SelectedStarterProfiles);

            SetState(GameFlowState.Ready);
        }
        catch (System.Exception exception)
        {
            Debug.LogError("GameFlowManager startup failed: " + exception.Message, this);
            SetState(GameFlowState.Failed);
        }
    }

    /// <summary>
    /// Verifies that all required startup dependencies are assigned.
    /// </summary>
    private bool HasRequiredReferences()
    {
        if (m_worldGenerator == null)
        {
            Debug.LogError("GameFlowManager is missing a WorldGenerator reference.", this);
            return false;
        }

        if (m_pawnGenerationManager == null)
        {
            Debug.LogError("GameFlowManager is missing a PawnGenerationManager reference.", this);
            return false;
        }

        if (m_pawnManager == null)
        {
            Debug.LogError("GameFlowManager is missing a PawnManager reference.", this);
            return false;
        }

        return true;
    }

    /// <summary>
    /// Updates the current game flow state and optionally logs the change.
    /// </summary>
    private void SetState(GameFlowState newState)
    {
        if (m_currentState == newState)
        {
            return;
        }

        m_currentState = newState;

        if (m_logStateChanges)
        {
            Debug.Log("GameFlow state changed to: " + m_currentState, this);
        }
    }
}